### PR TITLE
httpx for branch v4

### PR DESCRIPTION
**Pull request by robertcsapo**
- enable httpx support
- enable python 3.10 support
- remove hyper support

related to #233 (branch v5) and #238 (incorrect branch)
solving issue #220 (python 3.10)

### CODE REVIEW

**Review by babacarbasse — APPROVED** [review]

**Comment by bjinwright** [comment]
Can someone take a look at this please?

**Comment by robertcsapo** [comment]
@trevor-fauna

**Comment by trevor-fauna** [comment]
> @trevor-fauna

Hey @robertcsapo, apologies for the delay here, this slipped through the cracks. Let me follow up with the team and circle back with you shortly.

**Review by bbSnavy — APPROVED** [review]

**Comment by robertcsapo** [comment]
@trevor-fauna

**Comment by wildemat** [comment]
Thanks @robertcsapo for the contribution 👏 , apologies all for the delay on official support. It's been added in [4.5.0](https://github.com/fauna/faunadb-python/releases/tag/4.5.0)

**Pull request closed without merging**
